<?xml version="1.0"?>
<robot name="diff" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:include filename="$(find diff_description)/urdf/diff.gazebo" />
    <xacro:include filename="$(find diff_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find diff_description)/urdf/wheels.xacro" />


<!--ROBOT-->

<!--PROPERTIES-->
<xacro:property name="M_PI" value="3.14159"/>
<xacro:property name="M_PI_2" value="1.57079"/>
<xacro:property name="DEG_TO_RAD" value="0.017453"/>

<xacro:property name="base_height" value="0.02"/>
<xacro:property name="base_radius" value="0.15"/>
<xacro:property name="base_mass" value="5"/>

<xacro:property name="caster_f_height" value="0.04"/>
<xacro:property name="caster_f_radius" value="0.025"/>
<xacro:property name="caster_f_mass" value="0.5"/>

<xacro:property name="caster_b_height" value="0.04"/>
<xacro:property name="caster_b_radius" value="0.025"/>
<xacro:property name="caster_b_mass" value="0.5"/>

<xacro:property name="wheel_height" value="0.02"/>
<xacro:property name="wheel_radius" value="0.04"/>
<xacro:property name="wheel_mass" value="2.5"/>

<xacro:property name="base_x_origin_to_wheel_origin" value="0.25"/>
<xacro:property name="base_y_origin_to_wheel_origin" value="0.3"/>
<xacro:property name="base_z_origin_to_wheel_origin" value="0.0"/>

<xacro:property name="hokuyo_size" value="0.05"/>


<xacro:macro name="cylinder_inertia" params="m h r">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" 
    iyy="${m*(3*r*r + h*h)/12}" iyz="0" 
    izz="${m*r*r/2}"/>
</xacro:macro>


<link name="base_footprint">
    <inertial>
        <mass value="0.0001"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="0.001 0.001 0.001"/>
        </geometry>
    </visual>
</link>


<joint name="base_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
</joint>


<link name="base_link">
    <inertial>
        <mass value="${base_mass}"/>
        <origin xyz="0 0 0"/>
        <xacro:cylinder_inertia m="${base_mass}" 
                                r="${base_radius}" 
                                h="${base_height}"/>
    </inertial>
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
        <material name="white"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
    </collision>
</link>


<!--CASTER FRONT WHEEL-->
<link name="caster_front_link">
    <inertial>
        <mass value="${caster_f_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_f_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <origin xyz="0 0.02 0" rpy="0 0 0"/>
        <geometry>
            <sphere radius="${caster_f_radius}"/>
        </geometry>
    </collision>
</link>


<joint name="caster_front_joint" type="continuous">
    <origin xyz="0.115 0 0.007" rpy="${-M_PI/2} 0 0"/>
    <parent link="base_link"/>
    <child link="caster_front_link"/>
</joint>

  <gazebo reference="caster_front_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

<!--CASTER BACK WHEEL-->
<link name="caster_back_link">
    <inertial>
        <mass value="${caster_b_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
        <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_b_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <origin xyz="0.02 0.02 0" rpy="${M_PI/2} 0 0"/>
        <geometry>
            <sphere radius="${caster_b_radius}"/>
        </geometry>
    </collision>
</link>


<joint name="caster_back_joint" type="continuous">
    <origin xyz="-0.115 0 0.005" rpy="${-M_PI/2} 0 0"/>
    <parent link="base_link"/>
    <child link="caster_back_link"/>
</joint>



<!--HOKUYO LINK & HOKUYO-->
<link name="hokuyo_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
        </geometry>
        <material name="blue"/>
    </visual>
</link>


<joint name="hokuyo_joint" type="fixed">
    <origin xyz="${base_radius - hokuyo_size/2} 0 ${base_height+hokuyo_size/4}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="hokuyo_link"/>
</joint>


    <gazebo reference="hokuyo_link">

        <material>Gazebo/Blue</material>

        <turnGravityOff>true</turnGravityOff>
        <sensor name="hokuyo_laser" type="ray">
            <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>40</update_rate>

            <ray>
            <scan>
                <horizontal>
                <samples>720</samples>
                <resolution>1</resolution>
                <min_angle>-1.570796</min_angle>
                <max_angle>1.570796</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.1</min>
                <max>10.0</max>
                <resolution>0.01</resolution>
            </range>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
            </noise>
            </ray>

            <plugin name="hokuyo_laser" filename="libgazebo_ros_laser.so">
                <always_on>1</always_on>
                <topicName>/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
        </sensor>
    </gazebo>







<!--DRIVER CONTROLLER-->
<gazebo>
    <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller_front">
        <rosDebugLevel>Debug</rosDebugLevel>
        <publishWheelTF>1</publishWheelTF>
        <robotNamespace>/diff</robotNamespace>
        <publishTf>1</publishTf>
        <publishWheelJointState>false</publishWheelJointState>
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>

        <leftJoint>front_left_wheel_joint</leftJoint>
        <rightJoint>front_right_wheel_joint</rightJoint>

        <wheelSeperation>${2*base_radius}</wheelSeperation>
        <wheelDiameter>${2*wheel_radius}</wheelDiameter>
        <broadcastTF>1</broadcastTF>
        <wheelTorque>30</wheelTorque>
        <wheelAcceleration>1.8</wheelAcceleration>
        <commandTopic>cmd_vel</commandTopic>
        <odometryFrame>odom</odometryFrame>
        <odometryTopic>odom</odometryTopic>
        <robotBaseFrame>base_footprint</robotBaseFrame>

    </plugin>
</gazebo>


</robot>



